<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mst_barang_model extends CI_Model
{

    public $table = 'mst_barang';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('barang,datetime,harga,id,id_kategori,stok,ukuran,use_pricelist,use_stok');
        $this->datatables->from('mst_barang');
        //add this line for join
        //$this->datatables->join('table2', 'mst_barang.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('mst_barang/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('mst_barang/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('mst_barang/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('barang', $q);
	$this->db->or_like('datetime', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('use_pricelist', $q);
	$this->db->or_like('use_stok', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('barang', $q);
	$this->db->or_like('datetime', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('use_pricelist', $q);
	$this->db->or_like('use_stok', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mst_barang_model.php */
/* Location: ./application/models/Mst_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-24 01:57:57 */
/* http://harviacode.com */