<?php

if (!defined('BASEPATH')) {
 exit('No direct script access allowed');
}

class Pricelist_model extends CI_Model
{

 public $table = 'pricelist';
 public $id    = 'id';
 public $order = 'DESC';

 public function __construct()
 {
  parent::__construct();
 }

 // datatables
 public function json()
 {
  $this->datatables->select('range_pricelist.nama as nama_kasir,mst_barang.barang as nama_barang,pricelist.id,pricelist.range_pricelist,pricelist.id_barang,pricelist.harga,pricelist.keterangan');
  $this->datatables->from('pricelist');
  //add this line for join
  $this->datatables->join('mst_barang', 'pricelist.id_barang = mst_barang.id');
  $this->datatables->join('range_pricelist', 'pricelist.range_pricelist = range_pricelist.id');
  $this->datatables->group_by('mst_barang.id');
  $this->datatables->add_column('action', anchor(site_url('pricelist/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "
                " . anchor(site_url('pricelist/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_barang');
  return $this->datatables->generate();
 }

 // get all
 public function get_all()
 {
  $this->db->order_by($this->id, $this->order);
  return $this->db->get($this->table)->result();
 }

 // get data by id
 public function get_by_id($id)
 {
  $this->db->where('id_barang', $id);
  return $this->db->get($this->table)->row();
 }

 // get total rows
 public function total_rows($q = null)
 {
  $this->db->like('id', $q);
  $this->db->or_like('range_pricelist', $q);
  $this->db->or_like('id_barang', $q);
  $this->db->or_like('harga', $q);
  $this->db->or_like('keterangan', $q);
  $this->db->from($this->table);
  return $this->db->count_all_results();
 }

 // get data with limit and search
 public function get_limit_data($limit, $start = 0, $q = null)
 {
  $this->db->order_by($this->id, $this->order);
  $this->db->like('id', $q);
  $this->db->or_like('range_pricelist', $q);
  $this->db->or_like('id_barang', $q);
  $this->db->or_like('harga', $q);
  $this->db->or_like('keterangan', $q);
  $this->db->or_like('opsi1', $q);
  $this->db->or_like('opsi2', $q);
  $this->db->or_like('opsi3', $q);
  $this->db->or_like('opsi4', $q);
  $this->db->or_like('opsi5', $q);
  $this->db->limit($limit, $start);
  return $this->db->get($this->table)->result();
 }

 // insert data
 public function insert($data)
 {
  $this->db->insert_batch($this->table, $data);
 }

 // update data
 public function update($data)
 {
  //$this->db->where('id_barang', $id);
  $this->db->update_batch($this->table, $data, 'id');
 }

 // delete data
 public function delete($id)
 {
  $this->db->where($this->id, $id);
  $this->db->delete($this->table);
 }

}

/* End of file pricelist_model.php */
/* Location: ./application/models/pricelist_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-04 02:52:12 */
/* http://harviacode.com */
